name: Web | Build and Deploy
on:
  # ONLY triggers on master branch
  repository_dispatch:
    types: [content-update-build]
  push:
    branches: master
    paths: web/**
jobs:
    web:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v1
          - name: Use Node.js 12.x
            uses: actions/setup-node@v1
            with:
              node-version: 12.x
          - name: install n build
            env:
                SANITY_DEPLOY_STUDIO_TOKEN: ${{secrets.SANITY_AUTH_TOKEN}}
            run: |
                 yarn
                 npm run build-web
          - name: Deploy to netlify
            uses: netlify/actions/cli@master
            env:
              NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
              NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEB_SITE_ID }}
              SANITY_DEPLOY_STUDIO_TOKEN: ${{secrets.SANITY_AUTH_TOKEN}}
              app_local_sanityId: ${{secrets.SANITY_ID}}
              app_local_sanityDataset: ${{secrets.SANITY_DATASET}}
            with:
              args: deploy --dir=packages/tl-ph/public --prod
              secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID","SANITY_DEPLOY_STUDIO_TOKEN"]'
